import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Masthead from "../components/masthead";
import AboutUs from "../components/about";
import Skills from "../components/skills";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ecom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Masthead />
      <AboutUs />
      <Skills />
    </div>
  );
};

export default Home;
